<?xml version="1.0" encoding="utf-8"?><Database Name="StoreDB" Class="StoreDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=db-test-instance.c0pxf8y4tmfk.us-east-2.rds.amazonaws.com,1433;Initial Catalog=StoreDB;Persist Security Info=True;User ID=admin" SettingsObjectName="DesktopApp.My.MySettings" SettingsPropertyName="StoreDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="HashedPassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Users_Store" Member="Users_Stores" ThisKey="ID" OtherKey="UserID" Type="Users_Store" />
    </Type>
  </Table>
  <Table Name="dbo.Stores" Member="Stores">
    <Type Name="Store">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Store_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Store_Logo" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Store_Marketing_Line" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Store_Users_Store" Member="Users_Stores" ThisKey="ID" OtherKey="StoreID" Type="Users_Store" />
    </Type>
  </Table>
  <Table Name="dbo.Users_Stores" Member="Users_Stores">
    <Type Name="Users_Store">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Users_Store" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="Store_Users_Store" Member="Store" ThisKey="StoreID" OtherKey="ID" Type="Store" IsForeignKey="true" />
    </Type>
  </Table>
</Database>